name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

steps:
  - name: SSH and Deploy
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.SERVER_HOST }}
      username: ${{ secrets.SERVER_USERNAME }}
      password: ${{ secrets.SERVER_PASSWORD }}
      script: |
        cd ${{ secrets.APP_PATH }}
        git pull https://github.com/Matin-M/Savvy.git main
        docker-compose up -d --build
